### ISSUE TITLE
License

### ISSUE THREAD

**Issue by muhqu** [bdrister/dterm#1]
First of all, thanks a lot for open-sourcing DTerm! :tada: 

I just noticed that it's not clear under which License the Source Code of DTerm is provided. The provided [License.rtf](https://github.com/bdrister/dterm/blob/b95f5aa51884374eca2d0f534ae0d58cb40fe434/License.rtf) looks like the unchanged end-user license of the formerly paid version of DTerm. 

It would be great if you could be explicit under which [open-source license](http://choosealicense.com/licenses/) the source code is shared.

Thanks a lot!
– Mathias

**Comment by bdrister** [comment]
Good point. If I didn't document it anywhere, my intent was that it be unrestricted public domain.

**Comment by muhqu** [comment]
Thanks for clarification! …just opened a PR #2 to update the LICENSE file.
